name: cd

on:
    push:
      branches: [main]

jobs:
    deploy:
        permissions:
            contents: 'read'
            id-token: 'write'

        name: Deploy
        runs-on: ubuntu-latest
        
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
      
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.23.2"
            
            - name: Set up goose
              uses: mscno/setup-goose@v1

            - name: check diff
              run: git diff HEAD

            - name: Build
              run: scripts/buildprod.sh

            - uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'
        
            - name: 'Use gcloud CLI'
              run: 'gcloud info'          
              
            - name: build docker image
              run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-443421/notely-ar-repo/notely:latest
            
            - name: db migration
              run: scripts/migrateup.sh

            - name: Deploy to Cloud Run
              run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-443421/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-443421 --max-instances=4              

              